import math
from math import log
import torch
import torch.nn as nn
import torch.nn.functional as F
from mmdet.models import HEADS, build_loss
from mmcv.runner import force_fp32, BaseModule
from mmcv.ops.multi_scale_deform_attn import MultiScaleDeformableAttention
from mmcv.cnn.bricks.transformer import build_transformer_layer_sequence
from mmcv.cnn import Linear
from mmcv.cnn.bricks.conv_module import ConvModule
from mmcv.cnn.bricks.transformer import build_positional_encoding

from .tokenlearner import TokenLearner, TokenFuser
from .rcsample import Mlp

class MLN(nn.Module):
    ''' 
    from "https://github.com/exiawsh/StreamPETR"
    Args:
        c_dim (int): dimension of latent code c
        f_dim (int): feature dimension
    '''

    def __init__(self, c_dim, f_dim=256, use_ln=True):
        super().__init__()
        self.c_dim = c_dim
        self.f_dim = f_dim
        self.use_ln = use_ln

        self.reduce = nn.Sequential(
            nn.Linear(c_dim, f_dim),
            nn.ReLU(),
        )
        self.gamma = nn.Linear(f_dim, f_dim)
        self.beta = nn.Linear(f_dim, f_dim)
        if self.use_ln:
            self.ln = nn.LayerNorm(f_dim, elementwise_affine=False)
        self.init_weight()

    def init_weight(self):
        nn.init.zeros_(self.gamma.weight)
        nn.init.zeros_(self.beta.weight)
        nn.init.ones_(self.gamma.bias)
        nn.init.zeros_(self.beta.bias)

    def forward(self, x, c):
        if self.use_ln:
            x = self.ln(x)
        c = self.reduce(c)
        gamma = self.gamma(c)
        beta = self.beta(c)
        out = gamma * x + beta

        return out

class SELayerMLP(nn.Module):

    def __init__(self, channels, act_layer=nn.ReLU, gate_layer=nn.Sigmoid):
        super().__init__()
        self.mlp_reduce = nn.Linear(channels, channels)
        self.act1 = act_layer()
        self.mlp_expand = nn.Linear(channels, channels)
        self.gate = gate_layer()

    def forward(self, x, x_se):
        x_se = self.mlp_reduce(x_se)
        x_se = self.act1(x_se)
        x_se = self.mlp_expand(x_se)
        return x * self.gate(x_se)


def _align_osz_mask(osz_mask, size, device, dtype):
    """Move the (B, 3, H, W) OSZ mask onto the BEV feature grid.

    AXIS CONTRACT (fixed 2026-08-13 — was transposed 90°, see ISSUE.md P0-3):
      * OSZ masks are exported with ``axis-0 = ego-x`` (forward, 0.15 m/cell)
        and ``axis-1 = ego-y`` (left, 0.3 m/cell) — OSZ/config.py and
        OSZ/modules/bev_height_builder.py (``xi`` indexes axis-0, ``yi``
        axis-1); the online ``build_osz_mask_online`` (torch_pipeline.py)
        follows the same convention.
      * The ResWorld BEV feature map is the OPPOSITE: ``axis-0 = ego-y`` and
        ``axis-1 = ego-x`` — rcsample.py::create_grid_infos builds
        ``bev_coor`` so the x component varies along axis-1 (W) and the y
        component along axis-0 (H); col_attn samples it with
        ``spatial_shapes=(bev_w, bev_h)`` (x along W).
      * The mask is therefore TRANSPOSED here (before the resize): OSZ cell
        (i=xi, j=yi) must land on feature cell (row=yi, col=xi) — i.e. M.T.
        Keep OSZ as ``axis-0=x``; do NOT "fix" OSZ to ``axis-0=y``, or this
        transpose double-flips the mask back into the bug.
    """
    if osz_mask.dim() != 4:
        raise ValueError(
            f"osz_mask must be (B, 3, H, W), got {tuple(osz_mask.shape)}")
    m = osz_mask.to(device=device, dtype=dtype)
    m = m.transpose(-1, -2)              # OSZ axis-0=x -> feature axis-0=y
    if m.shape[-2:] != size:
        m = F.interpolate(m, size=size, mode="nearest")
    return m


class OcclusionAwareFusion(nn.Module):
    """Stage-2 occlusion injection: B~ = B + E_occ * M (residual form).

    ``E_occ`` is a learned occlusion offset generated by a 1x1 conv over
    the mask channels ``(osz_eye, osz_ground, semi)``, gated by the strict
    mask (``osz_eye`` channel). Residual form + zero-init (ISSUE.md P0-4,
    fixed 2026-08): the original replacement form ``B*(1-M) + E_occ*M``
    wiped the BEV feature inside the mask with a nearly position-invariant
    random embedding (a 1x1 conv sees no spatial context), so with the
    observed occ_frac ~0.45 almost half the BEV became homogeneous noise
    for col_attn — strictly worse than baseline. The residual form keeps
    the spatial information (identity at init, exactly baseline-equal at
    step 0) and lets E_occ learn only the occlusion OFFSET.
    An all-zero mask is the identity (baseline-equivalent).
    """

    def __init__(self, in_channels: int, mask_channels: int = 3):
        super(OcclusionAwareFusion, self).__init__()
        self.osz_embed = nn.Sequential(
            nn.Conv2d(mask_channels, in_channels, kernel_size=1),
            nn.ReLU(inplace=True),
        )
        # Zero-init the offset: at init B~ == B exactly (strict baseline
        # start; the offset is learned afterwards, see ISSUE.md P1-2).
        nn.init.zeros_(self.osz_embed[0].weight)
        nn.init.zeros_(self.osz_embed[0].bias)

    def forward(self, bev, mask):
        m = mask[:, :1]                # strict occlusion = osz_eye channel
        e_occ = self.osz_embed(mask)   # (bs, C, h, w) learned occlusion offset
        return bev + e_occ * m


def build_risk_field(pi, sigma, delta, mask, beta=2.0, w_sigma=1.0,
                     s_occ=None, gamma=1.0, risk_clamp=100.0):
    """Stage-4 occlusion-aware risk field (semantic-agnostic proxy, no params).

    Consumes the MHST aux outputs (design doc Stage 4):
        R^(k)    = w_sigma * sigma * ||dB^(k)||_2 * M      per-hypothesis risk
        R_exp    = sum_k pi_k R^(k)                        expected risk (CVaR)
        R_worst  = max_k R^(k)                             worst hypothesis (Minimax)
        U        = H(pi) / log K                           normalised prior entropy
        boost    = (1 + beta*U*M) * (1 + gamma*s_occ*M)    uncertainty-driven AND
                                                           occupancy-driven boost
    ``s_occ`` (if given) is the raw occlusion-occupancy logit from
    ``occ_head``; a sigmoid turns it into a probability in (0,1), which
    amplifies the risk where a dynamic object is predicted — turning raw
    "change intensity" into "threatening change".

    Gradient contract (ISSUE.md P0-2 / P2-3, fixed 2026-08): the risk field
    is a pure MEASUREMENT of the MHST distribution, never a training target
    for it. All distribution inputs (pi / sigma / delta / s_occ) are detached
    here — otherwise the three-way conflict (L_occ_halluc pushes ||dB|| up,
    L_div pushes hypotheses apart, L_plan_risk pushes ||dB|| down) collapses
    the hypotheses (dB->0, risk->0, Stage-5 dead) or lets the planner corrupt
    the distribution. The planner still receives gradient through the
    grid_sample GRID (spatial derivative of the risk field), so it learns to
    AVOID risk instead of erasing it.

    Bounded risk (ISSUE.md P0-6, fixed 2026-08): the field is clamped to
    ``risk_clamp`` (normal operating range is ~1-20, clamp at 100 leaves 5x
    headroom). A hypothesis whose posterior weight collapsed to ~0 (a
    "zombie hypothesis") loses its exposure-supervision gradient, so its
    ||dB|| can drift upward freely; R_worst = max_k would then inherit that
    unbounded magnitude and the risk-weighted planning losses (whose
    gradients scale with the field value) would cascade-explode the
    trajectory and the prior network (see the 2026-08-13 training log).
    The clamp keeps the planner's risk gradients bounded; per-hypothesis
    ||dB|| is separately capped by ``delta_clamp`` in OcclusionMHSTHead.

    Returns ``(B, 2, H, W)`` = ``[R~_exp, R~_worst]``. All-zero mask -> 0 risk.
    K=1: pi == 1 so H(pi) == 0 and U == 0 (no multi-hypothesis uncertainty).
    """
    # Detach every distribution input: risk measures, does not train.
    pi = pi.detach()
    sigma = sigma.detach()
    delta = delta.detach()
    if s_occ is not None:
        s_occ = s_occ.detach()
    B, K, C, H, W = delta.shape
    m = mask[:, :1]                                   # (B,1,H,W) osz_eye
    d_norm = delta.norm(dim=2)                        # (B,K,H,W) ||dB^k||_2
    # sigma's absolute scale is calibrated by L_uncertainty to the
    # feature-space error (can reach tens), so multiplying it straight into
    # the risk explodes the field (ISSUE.md P0-1; DIAG showed rf_occ≈30-50).
    # Use the bounded transform sigma/(1+sigma) ∈ [0,1) to keep the relative
    # ordering, and detach so risk never backprops into sigma — sigma stays
    # the calibration loss' contract, the risk field only consumes its
    # relative magnitude.
    sigma_risk = (sigma / (1.0 + sigma)).detach()
    r_k = w_sigma * sigma_risk * d_norm * m           # (B,K,H,W)
    r_exp = (pi * r_k).sum(dim=1)                     # (B,H,W)
    r_worst = r_k.max(dim=1).values                   # (B,H,W)
    log_k = log(max(K, 2))                            # K=1 -> U=0 (pi=1, H=0)
    h_pi = -(pi * torch.log(pi.clamp(min=1e-12))).sum(dim=1)   # (B,H,W)
    u = h_pi / log_k                                  # (B,H,W) in [0,1]
    boost = 1.0 + beta * u * m[:, 0]                  # (B,H,W)
    if s_occ is not None:
        # occ_head emits raw logits; sigmoid -> occupancy probability in
        # (0,1) so the boost stays bounded in [1, 1+gamma] (no negative
        # logit shrinking the risk, none large enough to explode it).
        s_occ = s_occ.sigmoid()                       # (B,1,H,W)
        boost = boost * (1.0 + gamma * s_occ[:, 0] * m[:, 0])
    r_exp = r_exp * boost
    r_worst = r_worst * boost
    field = torch.stack([r_exp, r_worst], dim=1)       # (B,2,H,W)
    if risk_clamp is not None and risk_clamp > 0:
        # ISSUE P0-6: bound the field so the risk-weighted planning
        # gradients (which scale with the field value) stay bounded.
        field = field.clamp(max=risk_clamp)
    return field


class OcclusionMHSTHead(nn.Module):
    """Stage-3 multi-hypothesis stochastic transition head (OARWM).

    Grafted AFTER the ResWorld deterministic residual path (right after
    ``pred_bev = tokenfuser(...) + bev_navi_embed``): inside occluded cells
    (mask channel 0 = osz_eye) the single deterministic guess is replaced
    by a K-hypothesis mixture; visible cells stay untouched::

        B_hat(x,y) = pred_bev(x,y)                              visible
                   = sum_k pi_k(x,y) * (pred_bev + dB^k)(x,y)   occluded

    Components (design doc Stage 3):
      * prior network g_prior: [pred_bev | mask] -> 1x1 conv -> multi-scale
        dilated neighbourhood (3x3 convs, dilation 1/2/4, receptive fields
        3/5/9 cells, aggregating N(x,y)) -> concat -> 1x1 conv -> K logits
        -> softmax = pi (B, K, H, W).
      * K-hypothesis residuals (MoE-style): one shared backbone
        (1x1 + 3x3 conv) then K independent expert 3x3 convs -> dB^k
        (B, K, C, H, W). K=1 is the single-hypothesis ablation.
      * uncertainty: sigma = softplus(s) + sigma_min (B, 1, H, W), kept
        for the calibration losses; it does NOT alter the fused output
        here (the mixture already is the expectation).

    An all-zero mask makes the head the identity (fused == pred_bev), so
    ``use_oarwm=False`` (or an empty mask) stays strictly baseline-exact.
    """

    def __init__(self, in_channels, k=3, sigma_min=0.1, mask_channels=3,
                 hidden=128, delta_clamp=10.0, sigma_max=10.0):
        super(OcclusionMHSTHead, self).__init__()
        self.k = k
        self.sigma_min = sigma_min
        # ISSUE P0-6 (2026-08): hard bounds on the hypothesis residuals and
        # the uncertainty. A hypothesis whose posterior weight collapses to
        # ~0 loses its exposure-supervision gradient, so its dB drifts
        # upward freely and R_worst = max_k inherits the unbounded magnitude
        # (2026-08-13 training explosion). Normal ||dB|| per element is
        # ~1-3 (||dB||_2 ~ 16-40); clamp at +-10 leaves ~4x headroom.
        self.delta_clamp = delta_clamp
        # Normal sigma is ~0.1-1 (calibrated to the exposure error); the
        # cap keeps var bounded so the mixture-likelihood constraint on dB
        # (gradient ~ 1/var) never fades.
        self.sigma_max = sigma_max

        # g_prior: mask + BEV context -> pi over K hypotheses.
        # Multi-scale dilated neighbourhood (dilation 1/2/4 -> receptive
        # fields 3/5/9 cells) so the prior sees the occluded-boundary
        # context N(x,y) beyond the 3-cell limit of a single 3x3 conv
        # (design doc Stage 3 limitation -> implemented fix).
        self.prior_conv1 = nn.Conv2d(
            in_channels + mask_channels, hidden, kernel_size=1)
        self.prior_d1 = nn.Conv2d(hidden, hidden, kernel_size=3,
                                  padding=1, dilation=1)
        self.prior_d2 = nn.Conv2d(hidden, hidden, kernel_size=3,
                                  padding=2, dilation=2)
        self.prior_d4 = nn.Conv2d(hidden, hidden, kernel_size=3,
                                  padding=4, dilation=4)
        self.prior_out = nn.Conv2d(hidden * 3, k, kernel_size=1)
        # Shared residual backbone, then one expert head per hypothesis.
        self.backbone = nn.Sequential(
            nn.Conv2d(in_channels, hidden, kernel_size=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(hidden, hidden, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
        )
        self.experts = nn.ModuleList([
            nn.Conv2d(hidden, in_channels, kernel_size=3, padding=1)
            for _ in range(k)
        ])
        # Zero-init the expert output layers (ISSUE.md P1-2, fixed 2026-08):
        # at init dB^k == 0, so the occluded patch == pred_bev and the fused
        # output is exactly the baseline at step 0 — no random perturbation
        # pollutes col_attn during early training; the hypotheses grow
        # gradually under the Stage-6 losses.
        for expert in self.experts:
            nn.init.zeros_(expert.weight)
            nn.init.zeros_(expert.bias)
        self.sigma_net = nn.Conv2d(hidden, 1, kernel_size=1)

    def forward(self, pred_bev, mask):
        m = mask[:, :1]                       # strict occlusion = osz_eye
        h0 = F.relu(
            self.prior_conv1(torch.cat([pred_bev, mask], dim=1)),
            inplace=True,
        )
        branches = [self.prior_d1(h0), self.prior_d2(h0), self.prior_d4(h0)]
        pi = self.prior_out(torch.cat(branches, dim=1))
        pi = pi.softmax(dim=1)                # (B, K, H, W)

        h = self.backbone(pred_bev)           # (B, hidden, H, W)
        delta = torch.stack(
            [expert(h) for expert in self.experts], dim=1)  # (B, K, C, H, W)
        if self.delta_clamp is not None and self.delta_clamp > 0:
            delta = delta.clamp(min=-self.delta_clamp, max=self.delta_clamp)

        occ = pred_bev.unsqueeze(1) + delta   # (B, K, C, H, W)
        patch = (occ * pi.unsqueeze(2)).sum(dim=1)          # (B, C, H, W)

        sigma = F.softplus(self.sigma_net(h)) + self.sigma_min
        if self.sigma_max is not None and self.sigma_max > 0:
            sigma = sigma.clamp(max=self.sigma_max)

        fused = pred_bev * (1 - m) + patch * m
        aux = {'pi': pi, 'sigma': sigma, 'delta': delta}
        return fused, aux


@HEADS.register_module()
class ResWorldHead(BaseModule):
    def __init__(self,
                #  *args,
                 grid_config,
                 num_frames=3,
                 embed_dims=256,
                 in_channels=256,
                 num_reg_fcs=2,
                 positional_encoding=None,
                 bev_h=30,
                 bev_w=30,
                 fut_ts=6,
                 fut_mode=6,
                 num_scenes=16,
                 latent_decoder=None,
                 res_latent_decoder=None,
                 way_decoder=None,
                 ego_fut_mode=3,
                 loss_plan_reg=dict(type='L1Loss', loss_weight=0.25),
                 ego_lcf_feat_idx=None,
                 valid_fut_ts=6,
                 # Injection gate: True iff any mask source is active
                 # (config: use_osz = use_osz_midas or use_osz_rcsample).
                 use_osz=False,
                 # Stage-3 OARWM switch: multi-hypothesis transition head
                 # (see OARWM_ResWorld.md Stage 3).
                 use_oarwm=False,
                 mhst_k=3,
                 mhst_sigma_min=0.1,
                 # ISSUE P0-6 (2026-08): hard bounds against the
                 # zombie-hypothesis explosion (see build_risk_field).
                 mhst_delta_clamp=10.0,
                 mhst_sigma_max=10.0,
                 # Stage-4 risk field (semantic-agnostic proxy, no params).
                 use_risk_field=False,
                 risk_beta=2.0,
                 risk_w_sigma=1.0,
                 risk_gamma=1.0,
                 risk_clamp=100.0,
                 # Stage-6 loss weights (0 disables the term).
                 loss_div_weight=0.1,
                 loss_occ_halluc_weight=1.0,
                 loss_uncertainty_weight=1.0,
                 loss_occ_gt_weight=1.0,
                 loss_occ_gt_pos_weight=5.0,
                 # risk-field grounding (design doc §6.2c): anchors the
                 # raw risk intensity to the exposure error e2 (zero extra
                 # data). 0 disables the term.
                 loss_risk_ground_weight=0.1,
                 # Stage-5 risk-weighted planning (approach A: no candidate
                 # selection; the risk field regularises the trajectory).
                 use_risk_plan=False,
                 # P0-1 (2026-08): risk terms are soft regularisers — their
                 # weights stay ~0.1 of loss_plan_reg (L1 weight 10) so the
                 # risk field steers the trajectory without overpowering the
                 # GT regression (0.1 / 0.1 / 0.05).
                 loss_plan_risk_weight=0.1,
                 loss_plan_cvar_weight=0.1,
                 loss_plan_info_weight=0.05,
                 cvar_beta=0.25,
                 # Risk terms are disabled for the first N epochs (sigma not
                 # yet calibrated by L_uncertainty, MHST randomly initialised
                 # — ISSUE.md P0-1/P1-2). The field is still sampled so the
                 # [DIAG] line keeps reporting r_cmd during warmup.
                 risk_plan_warmup_epochs=2,
                 # Linear ramp of the risk weights after warmup (epochs):
                 # the hard 0->1 switch made loss_plan_reg jump 0.53->1.24
                 # at the activation epoch (2026-08-13/14 log) — the ramp
                 # spreads the planner-vs-risk trade-off over N epochs so
                 # reg settles smoothly above init instead of spiking.
                 risk_plan_ramp_epochs=2,
                 # GT-risk upper-bound margin (design doc §5.1): the risk
                 # terms are relative to the GT trajectory's along-path risk,
                 # max(0, R(pred) - R(gt) - margin). 0 = pure upper bound;
                 # 5.0 ≈ 1/3 of the normal rf_occ range (15-30) tolerates
                 # risk-field noise around the GT path.
                 risk_plan_margin=5.0,
                 **kwargs):
        super(ResWorldHead, self).__init__()
        self.bev_h = bev_h
        self.bev_w = bev_w
        self.fp16_enabled = False
        self.fut_ts = fut_ts
        self.fut_mode = fut_mode
        self.embed_dims = embed_dims
        self.in_channels = in_channels
        self.num_reg_fcs = num_reg_fcs
        self.latent_decoder = latent_decoder
        self.res_latent_decoder = res_latent_decoder
        self.way_decoder = way_decoder
        self.positional_encoding = positional_encoding
        self.ego_fut_mode = ego_fut_mode
        self.ego_lcf_feat_idx = ego_lcf_feat_idx
        self.valid_fut_ts = valid_fut_ts
        self.num_scenes = num_scenes
        self.num_frames = num_frames
        self.grid_min = torch.tensor([grid_config['x'][0], grid_config['y'][0]])
        self.grid_max = torch.tensor([grid_config['x'][1], grid_config['y'][1]])
        self.grid_size = torch.tensor([grid_config['x'][2], grid_config['y'][2]])

        # Stage-2 OSZ switch. When False the occlusion fusion module is NOT
        # created at all: strictly baseline (zero extra params, and no
        # DDP 'unused parameter' failure under find_unused_parameters=False).
        self.use_osz = use_osz
        # Stage-3 OARWM switch: same rationale — the MHST head is only
        # created when active, so the strict baseline has zero extra params
        # and no DDP unused-parameter failure.
        self.use_oarwm = use_oarwm
        self.mhst_k = mhst_k
        self.mhst_sigma_min = mhst_sigma_min
        self.mhst_delta_clamp = mhst_delta_clamp
        self.mhst_sigma_max = mhst_sigma_max
        self.use_risk_field = use_risk_field
        self.risk_beta = risk_beta
        self.risk_w_sigma = risk_w_sigma
        self.risk_gamma = risk_gamma
        self.risk_clamp = risk_clamp
        # Stage-6 loss weights (per-term switch via weight=0).
        self.loss_div_weight = loss_div_weight
        self.loss_occ_halluc_weight = loss_occ_halluc_weight
        self.loss_uncertainty_weight = loss_uncertainty_weight
        self.loss_occ_gt_weight = loss_occ_gt_weight
        self.loss_occ_gt_pos_weight = loss_occ_gt_pos_weight
        self.loss_risk_ground_weight = loss_risk_ground_weight
        # Stage-5 risk-weighted planning.
        self.use_risk_plan = use_risk_plan
        self.loss_plan_risk_weight = loss_plan_risk_weight
        self.loss_plan_cvar_weight = loss_plan_cvar_weight
        self.loss_plan_info_weight = loss_plan_info_weight
        self.cvar_beta = cvar_beta
        self.risk_plan_warmup_epochs = risk_plan_warmup_epochs
        self.risk_plan_ramp_epochs = risk_plan_ramp_epochs
        self.risk_plan_margin = risk_plan_margin
        self._init_layers()
        self.loss_plan_reg = build_loss(loss_plan_reg)
        self.loss_plan_reg_init = build_loss(loss_plan_reg)
                
    def _init_layers(self):
        ego_fut_decoder = []
        ego_fut_dec_in_dim = self.embed_dims + len(self.ego_lcf_feat_idx) \
            if self.ego_lcf_feat_idx is not None else self.embed_dims
        for _ in range(self.num_reg_fcs):
            ego_fut_decoder.append(Linear(ego_fut_dec_in_dim, ego_fut_dec_in_dim))
            ego_fut_decoder.append(nn.ReLU())
        ego_fut_decoder.append(Linear(ego_fut_dec_in_dim, 2))
        self.ego_fut_decoder = nn.Sequential(*ego_fut_decoder)
        init_ego_fut_decoder = []
        for _ in range(self.num_reg_fcs):
            init_ego_fut_decoder.append(Linear(ego_fut_dec_in_dim, ego_fut_dec_in_dim))
            init_ego_fut_decoder.append(nn.ReLU())
        init_ego_fut_decoder.append(Linear(ego_fut_dec_in_dim, 2))
        self.init_ego_fut_decoder = nn.Sequential(*init_ego_fut_decoder)

        self.navi_embedding = nn.Embedding(3, self.embed_dims)
        self.navi_se = SELayerMLP(self.embed_dims)
        self.canbus_mlp = Mlp(18, self.embed_dims, self.embed_dims)
        self.canbus_se = SELayerMLP(self.embed_dims)
        self.bev_fusion_conv = ConvModule(self.in_channels * self.num_frames, self.in_channels, 
                                          kernel_size=3, padding=1)
        if self.use_osz:
            self.osz_fusion = OcclusionAwareFusion(self.in_channels)
        if self.use_oarwm:
            self.mhst = OcclusionMHSTHead(
                self.in_channels, k=self.mhst_k,
                sigma_min=self.mhst_sigma_min,
                delta_clamp=self.mhst_delta_clamp,
                sigma_max=self.mhst_sigma_max)
            if self.loss_occ_gt_weight > 0:
                # Occlusion occupancy head for L_occ_gt (dynamic content
                # supervision from rasterised detection-box GT).
                self.occ_head = nn.Conv2d(self.in_channels, 1, kernel_size=1)

        self.way_point = nn.Embedding(self.ego_fut_mode*self.fut_ts, self.embed_dims * 2)
        self.tokenlearner = TokenLearner(self.num_scenes, self.embed_dims * 2)
        self.res_tokenlearner = TokenLearner(self.num_scenes, self.embed_dims * 2)
        self.tokenfuser = TokenFuser(self.num_scenes, 256)

        self.latent_decoder = build_transformer_layer_sequence(self.latent_decoder)
        self.way_decoder = build_transformer_layer_sequence(self.way_decoder)
        self.res_latent_decoder = build_transformer_layer_sequence(self.res_latent_decoder)
        self.col_attn = MultiScaleDeformableAttention(self.embed_dims,
                                            num_points=8, num_levels=1)
        self.action_mln = MLN(6*2)
        self.positional_encoding = build_positional_encoding(
            self.positional_encoding)

    def init_weights(self):
        """Initialize weights of the DeformDETR head."""
        if self.latent_decoder is not None:
            for p in self.latent_decoder.parameters():
                if p.dim() > 1:
                    nn.init.xavier_uniform_(p) 
        if self.way_decoder is not None:
            for p in self.way_decoder.parameters():
                if p.dim() > 1:
                    nn.init.xavier_uniform_(p)
        if self.res_latent_decoder is not None:
            for p in self.res_latent_decoder.parameters():
                if p.dim() > 1:
                    nn.init.xavier_uniform_(p) 

    @force_fp32(apply_to=('bev_feats'))
    def forward(self,
                bev_inputs,
                img_metas,
                prev_bev=None,
                only_bev=False,
                ego_his_trajs=None,
                ego_lcf_feat=None,
                cmd=None,
                osz_mask=None,
                gt_bev_next=None
            ):
        
        bev_feats, can_bus_infos = bev_inputs
        bt, c, h, w = bev_feats.shape
        bs = bt // self.num_frames
        dtype = bev_feats[0].dtype
        device = bev_feats[0].device
        can_bus_infos = self.canbus_mlp(can_bus_infos.permute(1, 0, 2)).view(bt, 1, self.in_channels)
        bev_embed = self.canbus_se(bev_feats.view(bt, c, h*w).permute(0, 2, 1), can_bus_infos)
        bev_embed_single = bev_embed.clone()
        bev_embed = bev_embed.permute(0, 2, 1).view(self.num_frames, bs, c, h, w).permute(1, 0, 2, 3, 4)
        bev_embed = self.bev_fusion_conv(bev_embed.reshape(bs, self.num_frames * c, h, w))
        if self.use_osz and osz_mask is not None:
            # Stage-2 occlusion-aware injection (OARWM). Mask channels are
            # (osz_eye, osz_ground, semi). All-zeros = identity.
            m = _align_osz_mask(osz_mask, (h, w), device, dtype)
            bev_embed = self.osz_fusion(bev_embed, m)
        bev_feats = bev_feats.view(self.num_frames, bs, c, h, w)


        bev_mask = torch.zeros((bs, self.bev_h, self.bev_w),
                               device=bev_feats.device).to(dtype)
        bev_pos = self.positional_encoding(bev_mask).to(dtype)

        pos_embd = bev_pos.flatten(2).permute(0, 2, 1)
        bev_embed = bev_embed.reshape(bs, c, h * w).permute(0, 2, 1)
        # res_embed = res_embed.reshape(bs, c, h * w).permute(0, 2, 1)

        navi_embed = []
        for bidx in range(bs):
            cmd_idx = torch.nonzero(cmd[bidx, 0, 0])[0, 0]
            navi_embed.append(self.navi_embedding.weight[cmd_idx][None, None])
        navi_embed = torch.cat(navi_embed, dim=0)

        bev_navi_embed = self.navi_se(bev_embed, navi_embed)

        bev_query = torch.cat((bev_navi_embed, pos_embd), -1)

        learned_latent_query, selected = self.tokenlearner(bev_query)
        _, res_selected = self.res_tokenlearner(bev_query)
        bev_embed_single = torch.cat((bev_embed_single, pos_embd.repeat(self.num_frames,1,1)), -1)
        bev_embed_single = torch.einsum('bsi,bic->bsc', res_selected.repeat(self.num_frames,1,1), bev_embed_single)\
                            .view(self.num_frames, bs, learned_latent_query.shape[1],learned_latent_query.shape[2])
        res_latent_query_all = bev_embed_single[:-1] - bev_embed_single[1:]

        learned_latent_query=learned_latent_query.permute(1, 0, 2)
        latent_query, latent_pos = torch.split(
            learned_latent_query, self.embed_dims, dim=2)

        latent_query = self.latent_decoder(
                query=latent_query,
                key=latent_query,
                value=latent_query,
                query_pos=latent_pos,
                key_pos=latent_pos)

        way_point = self.way_point.weight.to(dtype)
        wp_pos, way_point = torch.split(
            way_point, self.embed_dims, dim=1)

        wp_pos = wp_pos.unsqueeze(0).expand(bs, -1, -1)
        way_point = way_point.unsqueeze(0).expand(bs, -1, -1)
        wp_pos = wp_pos.permute(1, 0, 2)
        way_point = way_point.permute(1, 0, 2)

        way_point = self.way_decoder(
                query=way_point,
                key=latent_query,
                value=latent_query,
                query_pos=wp_pos,
                key_pos=latent_pos)
        init_ego_trajs = self.init_ego_fut_decoder(way_point)
        init_ego_trajs = init_ego_trajs.permute(1, 0, 2). view(bs, 
                                                    self.ego_fut_mode, self.fut_ts, 2)
        init_ego_coords = init_ego_trajs.cumsum(dim=2).view(bs, -1, 2)
        init_ego_coords = (init_ego_coords - self.grid_min.to(device).view(1, 1, 2)) / \
                            self.grid_size.to(device).view(1, 1, 2) / 200
        init_wp_vector = []
        for bidx in range(bs):
            cmd_idx = torch.nonzero(cmd[bidx, 0, 0])[0, 0]
            init_wp_vector.append(init_ego_trajs[bidx, cmd_idx, ...].reshape(1, 1, 12))  
        init_wp_vector = torch.cat(init_wp_vector, dim=1)

        reference_points = init_ego_coords.unsqueeze(2)
        spatial_shapes = torch.tensor([self.bev_w, self.bev_h]).view(1, 2).to(device)
        level_start_index = torch.tensor([0]).to(device)

        res_latent_query=res_latent_query_all[0].permute(1, 0, 2)
        res_latent_query, res_latent_pos = torch.split(
            res_latent_query, self.embed_dims, dim=2)
        res_latent_query = self.action_mln(res_latent_query, init_wp_vector)
        res_latent_query = self.res_latent_decoder(
                query=res_latent_query,
                key=res_latent_query,
                value=res_latent_query,
                query_pos=res_latent_pos,
                key_pos=res_latent_pos)
        
        pred_bev = self.tokenfuser(res_latent_query.permute(1, 0, 2), bev_navi_embed) + bev_navi_embed

        mhst_aux = None
        if self.use_oarwm and osz_mask is not None:
            # Stage-3 MHST: K-hypothesis mixture inside occluded cells.
            #
            # Layout contract (verified against the pipeline):
            #  * pred_bev from the tokenfuser is ALWAYS (B, H*W, C) — the
            #    ResWorld residual path flattens the BEV grid (H=W=100 here,
            #    see the bev_query <-> pos_embd cat) row-major into a
            #    sequence that col_attn consumes via permute(1,0,2).
            #  * MHST is a per-cell convolution head (prior/backbone/experts
            #    are Conv2d), so it operates on the SAME data in 2D grid
            #    form (B, C, H, W). We restore the grid, run the head, and
            #    flatten back before col_attn — a lossless layout change,
            #    not an alternative representation.
            #  * The OSZ mask is (B, 3, 200, 200) (grid_config); the BEV
            #    feature is 100x100, so the mask is downsampled (nearest).
            pb = pred_bev.permute(0, 2, 1).reshape(bs, c, h, w)
            # Gradient contract (ISSUE.md P1-4, completed 2026-08-23):
            # detach the world-model BEV before the MHST / occ heads
            # consume it. P1-4 stopped the additive b_hat branch but left
            # the conv-INPUT path live — the Stage-6 exposure losses
            # (halluc / uncertainty / ground / div / occ_gt) flowed through
            # prior_conv / backbone / experts / sigma_net / occ_head back
            # into pred_bev, pulling the deterministic world model away
            # from serving the planner (occ_frac ~0.67 made this a
            # map-wide distortion, the top suspect for the persistent L2
            # gap vs baseline). With this detach, Stage-6 trains ONLY the
            # MHST/occ heads; the world model is shaped by planning (and
            # depth) losses alone.
            pb = pb.detach()
            mhst_mask = _align_osz_mask(osz_mask, (h, w), device, pb.dtype)
            # (design doc §3.3): col_attn keeps the CLEAN pred_bev — the
            # multi-hypothesis mixture no longer perturbs the shared BEV
            # features consumed by trajectory refinement. The hypotheses
            # reach the planner ONLY via the explicit risk field (Stage 4),
            # so the fused output is computed for its aux (pi/sigma/delta)
            # and then intentionally dropped here.
            mhst_aux = self.mhst(pb, mhst_mask)[1]
            # Extra aux for the Stage-6 losses: un-fused 4D pred_bev, the
            # occlusion occupancy prediction and the aligned osz_eye mask.
            mhst_aux['pred_bev_4d'] = pb
            mhst_aux['mask'] = mhst_mask[:, :1]
            if hasattr(self, 'occ_head'):
                mhst_aux['s_occ'] = self.occ_head(pb)
        elif self.use_oarwm:
            # Fail loudly: MHST without a mask source would silently produce
            # an identity (and leave all its params unused under DDP). The
            # config asserts use_oarwm -> use_osz, so this is a logic error.
            raise ValueError(
                "use_oarwm=True but osz_mask is None — MHST requires a "
                "mask source (use_osz_midas or use_osz_rcsample).")

        risk_field = None
        if self.use_risk_field and mhst_aux is not None and osz_mask is not None:
            # Stage-4 risk field: semantic-agnostic proxy from the MHST aux
            # (pi / sigma / delta), grid-aligned with the BEV feature. No
            # learnable parameters — a pure function of the distribution.
            rf_mask = _align_osz_mask(osz_mask, (h, w), device, pred_bev.dtype)
            risk_field = build_risk_field(
                mhst_aux['pi'], mhst_aux['sigma'], mhst_aux['delta'],
                rf_mask, beta=self.risk_beta, w_sigma=self.risk_w_sigma,
                s_occ=mhst_aux.get('s_occ'), gamma=self.risk_gamma,
                risk_clamp=self.risk_clamp)

        way_point = self.col_attn(
                query=way_point,
                key=pred_bev.permute(1, 0, 2),
                value=pred_bev.permute(1, 0, 2),
                reference_points=reference_points,
                spatial_shapes=spatial_shapes,
                level_start_index=level_start_index) 

        outputs_ego_trajs = self.ego_fut_decoder(way_point)
        outputs_ego_trajs = outputs_ego_trajs.permute(1, 0, 2). view(bs, 
                                                      self.ego_fut_mode, self.fut_ts, 2)

        wp_vector = []
        for bidx in range(bs):
            cmd_idx = torch.nonzero(cmd[bidx, 0, 0])[0, 0]
            wp_vector.append(outputs_ego_trajs[bidx, cmd_idx, ...].reshape(1, 1, 12))  
        wp_vector = torch.cat(wp_vector, dim=1)

        outs = {
            'bev_embed': bev_embed,
            'pred_bev': pred_bev,
            'scene_query': latent_query,
            'wp_vector': wp_vector,
            # 'act_query': act_query,
            # 'act_pos': act_pos,
            'ego_fut_preds': outputs_ego_trajs,
            # 'ego_fut_preds': init_ego_trajs,
            'init_ego_fut_preds': init_ego_trajs,
        }
        if mhst_aux is not None:
            # Stage-3 aux outputs (pi / sigma / delta), consumed by the
            # Stage-6 losses (L_occ_halluc / L_div / L_uncertainty).
            outs['mhst'] = mhst_aux
        if risk_field is not None:
            # Stage-4 risk field [R~_exp, R~_worst] (B, 2, H, W), consumed
            # by the Stage-5 planner (Minimax -> worst, CVaR -> exp).
            outs['risk_field'] = risk_field
        if gt_bev_next is not None:
            # Next-frame exposure ground truth (current ego frame), used by
            # the Stage-6 losses (L_occ_halluc / L_uncertainty).
            outs['gt_bev_next'] = gt_bev_next

        return outs
    
    @force_fp32(apply_to=('preds_dicts'))
    def loss(self,
             gt_bboxes_list,
             gt_labels_list,
             map_gt_bboxes_list,
             map_gt_labels_list,
             preds_dicts,
             ego_fut_gt,
             ego_fut_masks,
             ego_fut_cmd,
             gt_attr_labels,
             gt_bboxes_ignore=None,
             map_gt_bboxes_ignore=None,
             img_metas=None):

        ego_fut_preds = preds_dicts['ego_fut_preds']
        init_ego_fut_preds = preds_dicts['init_ego_fut_preds']
        loss_dict = dict()

        # Planning Loss
        ego_fut_gt = ego_fut_gt.squeeze(1)
        ego_fut_masks = ego_fut_masks.squeeze(1).squeeze(1)
        ego_fut_cmd = ego_fut_cmd.squeeze(1).squeeze(1)

        ego_fut_gt = ego_fut_gt.unsqueeze(1).repeat(1, self.ego_fut_mode, 1, 1)
        loss_plan_l1_weight = ego_fut_cmd[..., None, None] * ego_fut_masks[:, None, :, None]
        loss_plan_l1_weight = loss_plan_l1_weight.repeat(1, 1, 1, 2)

        loss_plan_l1 = self.loss_plan_reg(
            ego_fut_preds,
            ego_fut_gt,
            loss_plan_l1_weight
        )

        loss_plan_l1_init = self.loss_plan_reg_init(
            init_ego_fut_preds,
            ego_fut_gt,
            loss_plan_l1_weight
        )
      
        loss_dict['loss_plan_reg'] = loss_plan_l1
        loss_dict['loss_plan_reg_init'] = loss_plan_l1_init

        # ---- Stage-3/4 related losses (design doc §6.2/6.2b/6.3/6.4) ----
        mhst = preds_dicts.get('mhst')
        if mhst is not None:
            pi = mhst['pi']               # (B, K, H, W)
            sigma = mhst['sigma']         # (B, 1, H, W)
            delta = mhst['delta']         # (B, K, C, H, W)
            mask = mhst['mask']           # (B, 1, H, W) osz_eye
            pb = mhst['pred_bev_4d']      # (B, C, H, W) un-fused pred_bev

            occ_mask = mask > 0
            n_occ = occ_mask.float().sum().clamp(min=1.0)

            # 6.3 L_div: minimise pairwise cosine similarity of the hypothesis
            # residuals (maximise separation). Unit-normalised -> bounded in
            # [-1,1] and gradient-stable (no exploding d2/base ratio).
            # Fixed 2026-08 (ISSUE.md P2-4): (a) computed on OCCLUDED cells
            # only — visible cells never enter the fused output, so pushing
            # their hypotheses apart wasted capacity and had no opposing
            # supervision; (b) clamped at 0 — negatively correlated (already
            # separated) pairs get no reward, the term has a lower bound.
            if self.loss_div_weight > 0 and delta.shape[1] > 1:
                delta_occ = delta * occ_mask.float().unsqueeze(1)  # (B,K,C,H,W)
                flat = delta_occ.flatten(2)                # (B,K,D)
                unit = flat / flat.norm(
                    dim=2, keepdim=True).clamp(min=1e-6)   # (B,K,D)
                cos_pairs = []
                for k1 in range(delta.shape[1]):
                    for k2 in range(k1 + 1, delta.shape[1]):
                        cos_pairs.append(
                            (unit[:, k1] * unit[:, k2]).sum(dim=1).mean())
                loss_dict['loss_div'] = (
                    torch.stack(cos_pairs).mean().clamp(min=0.0)
                    * self.loss_div_weight)

            gt_next = preds_dicts.get('gt_bev_next')   # (B, C, H, W)
            if gt_next is not None:
                # exposure error per cell (mean over C), used by 6.4.
                # P1-4 (fixed 2026-08): the exposure losses train ONLY the
                # MHST head (pi / dB / sigma) — `pb` (the deterministic
                # tokenfuser output) is stop-grad'ed here and `e2` is
                # detached entirely, so the world-model latent residual path
                # is not pulled away from serving the planner, and sigma is
                # calibrated against a FIXED error target (no sigma<->e2
                # mutual-pull loop: |sigma - e2| with a live e2 would drag
                # the error toward sigma instead of calibrating sigma to it).
                b_hat = pb.detach() + (pi.unsqueeze(2) * delta).sum(dim=1)
                # P0-6: cap the calibration TARGET at sigma_max — an outlier
                # exposure error must not drag the |sigma - e2| magnitude
                # (and the sigma it calibrates) to arbitrary values; sigma
                # is separately capped at sigma_max in OcclusionMHSTHead.
                e2 = (b_hat.detach() - gt_next).pow(2).mean(
                    dim=1, keepdim=True).clamp(max=self.mhst_sigma_max)

                # 6.2 L_occ_halluc: negative log mixture likelihood over the
                # occluded cells (EM-style fit of pi / delta / sigma).
                if self.loss_occ_halluc_weight > 0:
                    b_k = pb.detach().unsqueeze(1) + delta   # (B,K,C,H,W)
                    diff2 = (b_k - gt_next.unsqueeze(1)).pow(2).mean(dim=2)
                    var = sigma + 1e-6
                    log_p = -0.5 * (diff2 / var +
                                    torch.log(var) +
                                    log(2 * math.pi))
                    log_mix = torch.logsumexp(
                        log_p + torch.log(pi.clamp(min=1e-12)), dim=1)
                    # occ_mask.squeeze(1) -> (B,H,W) matches log_mix
                    loss_dict['loss_occ_halluc'] = (
                        -(log_mix * occ_mask.float().squeeze(1)).sum() / n_occ
                        * self.loss_occ_halluc_weight)

                # 6.4 L_uncertainty: calibrate sigma against exposure error.
                if self.loss_uncertainty_weight > 0:
                    loss_dict['loss_uncertainty'] = (
                        ((sigma - e2).abs() * occ_mask.float()).sum() / n_occ
                        * self.loss_uncertainty_weight)

                # 6.2c L_risk_ground (design doc §4/§6.2): anchor the
                # RAW risk intensity (sigma-weighted hypothesis magnitude,
                # NOT detached — grounding belongs to the distribution-
                # shaping losses, the P0-2 detach contract only guards the
                # risk-field -> planner direction) to the real exposure
                # change e2. The risk field thus becomes an unbiased
                # "future content change" estimate: low along the GT path,
                # so the GT-risk upper bound (§5.1) stays dormant there.
                if self.loss_risk_ground_weight > 0:
                    r_raw = (sigma / (1.0 + sigma)) * delta.norm(
                        dim=2).mean(dim=1, keepdim=True) * mask  # (B,1,H,W)
                    loss_dict['loss_risk_ground'] = (
                        ((r_raw - e2).pow(2) * mask).sum() / n_occ
                        * self.loss_risk_ground_weight)

            # 6.2b L_occ_gt: BCE of the occupancy head against rasterised
            # detection-box BEV occupancy (occluded cells only).
            if self.loss_occ_gt_weight > 0 and hasattr(self, 'occ_head') \
                    and 's_occ' in mhst:
                s_occ = mhst['s_occ']     # (B, 1, H, W)
                occ_gt = self._rasterise_boxes_bev(
                    gt_bboxes_list, img_metas, device=s_occ.device)
                # pos_weight penalises missed occupancies -> learns the
                # occluded dynamic content instead of the all-zero trivial
                # solution (class imbalance: occluded cells are mostly empty).
                pos = torch.as_tensor(
                    self.loss_occ_gt_pos_weight, dtype=s_occ.dtype,
                    device=s_occ.device)
                loss_dict['loss_occ_gt'] = (
                    F.binary_cross_entropy_with_logits(
                        s_occ, occ_gt, pos_weight=pos, reduction='none')
                    * occ_mask.float()
                ).sum() / n_occ * self.loss_occ_gt_weight

        # ---- Stage-5 risk-weighted planning (design doc §5, approach A) ----
        # No candidate selection: the risk field (R_worst / R_exp) directly
        # regularises the predicted trajectory so the network learns to avoid
        # high-risk (ghost-probe) regions end-to-end. R_worst is the over-K
        # max (minimax semantics); the step-risk tail gives CVaR; the
        # end-risk vs GT-end risk drop rewards active sensing (info gain).
        risk_field = preds_dicts.get('risk_field')   # (B, 2, H, W)
        if self.use_risk_plan and risk_field is not None:
            # Risk terms are disabled for the first risk_plan_warmup_epochs
            # epochs (sigma not yet calibrated, MHST randomly initialised —
            # ISSUE.md P0-1/P1-2). The field is still sampled below so the
            # [DIAG] line keeps reporting r_cmd during warmup.
            risk_active = getattr(self, 'epoch', -1) >= self.risk_plan_warmup_epochs
            # Linear ramp after warmup (0 -> 1 over risk_plan_ramp_epochs):
            # avoids the hard-switch spike in loss_plan_reg observed at the
            # activation epoch (0.53 -> 1.24 in the 2026-08-13 log).
            risk_scale = 1.0
            if risk_active and self.risk_plan_ramp_epochs > 0:
                risk_scale = min(
                    1.0,
                    (getattr(self, 'epoch', self.risk_plan_warmup_epochs)
                     - self.risk_plan_warmup_epochs + 1.0)
                    / self.risk_plan_ramp_epochs)
            # absolute trajectory coords (per-step increments -> cumsum)
            traj_abs = ego_fut_preds.cumsum(dim=2)    # (B, M, T, 2)
            device = traj_abs.device
            gmin = self.grid_min.to(device)
            gsz = self.grid_size.to(device)
            # normalised grid coords (col_attn convention: /grid_size/200)
            nx = (traj_abs[..., 0] - gmin[0]) / (gsz[0] * 200)   # 0-1
            ny = (traj_abs[..., 1] - gmin[1]) / (gsz[1] * 200)
            grid = torch.stack([nx * 2 - 1, ny * 2 - 1], dim=-1)  # (B,M,T,2)
            # GT trajectory risk (design doc §5): ego_fut_gt is per-step
            # INCREMENTS (it is matched against the incremental predictions
            # by the L1 above and cumsum'ed in the test-time metric), so
            # cumsum it to absolute coords first — its along-path risk is
            # the "acceptable safety" upper bound.
            traj_abs_gt = ego_fut_gt.cumsum(dim=2)      # (B, M, T, 2) absolute
            nx_gt = (traj_abs_gt[..., 0] - gmin[0]) / (gsz[0] * 200)
            ny_gt = (traj_abs_gt[..., 1] - gmin[1]) / (gsz[1] * 200)
            grid_gt = torch.stack(
                [nx_gt * 2 - 1, ny_gt * 2 - 1], dim=-1)          # (B,M,T,2)
            B, M, T, _ = grid.shape
            # Sample both risk fields for pred and GT in one call each
            # (channel 0 = R_exp, 1 = R_worst).
            sampled = F.grid_sample(
                risk_field, grid.reshape(B, M * T, 1, 2),
                mode='bilinear', align_corners=True).reshape(B, M * T, 2)
            sampled_gt = F.grid_sample(
                risk_field, grid_gt.reshape(B, M * T, 1, 2),
                mode='bilinear', align_corners=True).reshape(B, M * T, 2)
            r_worst = sampled[..., 1].reshape(B, M, T)
            r_exp = sampled[..., 0].reshape(B, M, T)
            r_worst_gt = sampled_gt[..., 1].reshape(B, M, T)
            r_exp_gt = sampled_gt[..., 0].reshape(B, M, T)
            # command-weighted: only the commanded trajectory is supervised
            cmd_w = ego_fut_cmd  # (B, M) one-hot (squeezed above)
            fut_w = ego_fut_masks.float()             # (B, T) valid flags
            r_cmd = (r_worst * cmd_w.unsqueeze(-1)).sum(dim=1)   # (B, T)
            re_cmd = (r_exp * cmd_w.unsqueeze(-1)).sum(dim=1)    # (B, T)
            r_gt_cmd = (r_worst_gt * cmd_w.unsqueeze(-1)).sum(dim=1)  # (B,T)
            re_gt_cmd = (r_exp_gt * cmd_w.unsqueeze(-1)).sum(dim=1)   # (B,T)
            margin = self.risk_plan_margin

            if risk_active:
                # relative form (design doc §5.1): GT risk is the
                # acceptable-safety upper bound; only steps RISKIER than the
                # human demo are penalised — when pred ~= GT the term is 0
                # (zero gradient) and the open-loop L2 regression trains
                # undisturbed. (risk_scale: linear ramp after warmup.)
                loss_dict['loss_plan_risk'] = (
                    ((r_cmd - r_gt_cmd - margin).clamp(min=0) * fut_w).sum()
                    / fut_w.sum().clamp(min=1.0)
                    * self.loss_plan_risk_weight * risk_scale)

                # CVaR: tail of the commanded trajectory's step-risk values,
                # relative to the GT tail. P2-1 (fixed 2026-08): fut_w zeroes
                # the INVALID steps BEFORE topk.
                if self.loss_plan_cvar_weight > 0:
                    k = max(1, int(math.ceil(T * self.cvar_beta)))
                    r_cmd_valid = r_cmd * fut_w       # (B, T) invalid -> 0
                    r_gt_valid = r_gt_cmd * fut_w     # (B, T) invalid -> 0
                    topk_pred = r_cmd_valid.topk(k, dim=1).values.mean(dim=1)
                    topk_gt = r_gt_valid.topk(k, dim=1).values.mean(dim=1)
                    loss_dict['loss_plan_cvar'] = (
                        (topk_pred - topk_gt - margin).clamp(min=0).mean()
                        * self.loss_plan_cvar_weight * risk_scale)

                # info gain (relative form): the ego-origin risk is
                # IDENTICAL for both trajectories, so the relative bound
                # reduces to the end-risk difference. The end is the LAST
                # VALID step (fut_w), not the padded one (ISSUE P1-1).
                if self.loss_plan_info_weight > 0:
                    last_idx = (fut_w.sum(dim=1).long() - 1).clamp(min=0)
                    r_end = re_cmd.gather(1, last_idx.unsqueeze(1)).squeeze(1)
                    r_end_gt = re_gt_cmd.gather(
                        1, last_idx.unsqueeze(1)).squeeze(1)
                    info_penalty = (r_end - r_end_gt).clamp(min=0).mean()
                    loss_dict['loss_plan_info'] = (
                        info_penalty * self.loss_plan_info_weight * risk_scale)

        # ---- [DIAG] temporary risk-planning diagnostics (remove after tuning) ----
        # Caches a per-iter diagnostic line; DiagLoggerHook prints it at the
        # same cadence as the TextLoggerHook loss output (log_config interval,
        # see projects/mmdet3d_plugin/resworld/hooks/custom_hooks.py). Tracks
        # Stage-5 activation and online-mask quality (ISSUE.md P0-1 / P1-3).
        if self.use_risk_plan and risk_field is not None and mhst is not None:
            msk = mhst['mask'] > 0                   # (B,1,H,W) osz_eye
            occ_frac = msk.float().mean().item()     # occluded-cell fraction
            rf_mean = risk_field.mean().item()       # overall risk mean
            rf_occ = ((risk_field * msk).sum()
                      / msk.float().sum().clamp(min=1.0)).item()
            rc = r_cmd.detach()                      # (B,T) commanded risk
            rgc = r_gt_cmd.detach()                  # (B,T) GT commanded risk
            # Trajectory-shape diagnostics (over-conservatism probe,
            # 2026-08-16 eval: L2 ~0.57 avg & CR ~1e-4 -> suspected
            # shrunken/slow trajectories; these two stats make the
            # shrinkage visible in the training log):
            #   traj_end = mean end displacement (m) of the commanded traj
            #   traj_step = mean step size (m) of the commanded traj
            tr = (traj_abs * cmd_w.unsqueeze(-1).unsqueeze(-1)).sum(dim=1)
            tr = tr * fut_w.unsqueeze(-1)            # (B,T,2) valid steps
            traj_end = tr[:, -1].norm(dim=-1).mean().item()
            traj_step = (tr[:, 1:] - tr[:, :-1]).norm(dim=-1).mean().item()
            self._diag_msg = (
                f"[DIAG] occ_frac={occ_frac:.3f} rf_mean={rf_mean:.5f} "
                f"rf_occ={rf_occ:.5f} r_cmd_mean={rc.mean().item():.5f} "
                f"r_gt_cmd_mean={rgc.mean().item():.5f} "
                f"r_cmd_pos_frac={(rc > 0).float().mean().item():.3f} "
                f"traj_end={traj_end:.2f}m traj_step={traj_step:.2f}m")

        return loss_dict

    def _rasterise_boxes_bev(self, gt_bboxes_list, img_metas, device):
        """Rasterise LiDAR-frame 3D boxes into a binary BEV occupancy map
        (B, 1, H, W) on the head's BEV grid. Axis-aligned bottom-rectangle
        approximation via the box corners' bounding box, transformed to the
        ego frame with ``img_metas[..]['lidar2ego']`` when available."""
        B = len(gt_bboxes_list)
        occ = torch.zeros(B, 1, self.bev_h, self.bev_w, device=device)
        x_min, y_min = float(self.grid_min[0]), float(self.grid_min[1])
        x_max, y_max = float(self.grid_max[0]), float(self.grid_max[1])
        for b in range(B):
            boxes = gt_bboxes_list[b]
            if boxes is None or len(boxes) == 0:
                continue
            c = boxes.corners
            if c.dim() == 2:
                c = c.view(-1, 8, 3)               # defensive: flattened
            corners = c[:, :4, :2]                 # (N,4,2) bottom rect, LiDAR
            corners = corners.to(device=device).float()
            l2e = None
            if img_metas is not None and len(img_metas) > b:
                l2e = img_metas[b].get('lidar2ego')
            if l2e is not None:
                l2e_t = torch.as_tensor(
                    l2e, dtype=corners.dtype, device=corners.device)
                zero = torch.zeros_like(corners[..., :1])
                one = torch.ones_like(corners[..., :1])
                # homogeneous (x, y, 0, 1): (N,4,4)
                ch = torch.cat([corners[..., :1], corners[..., 1:2],
                                zero, one], dim=-1)
                # explicit einsum: 'ij,bkj->bki' — l2e (4,4) per point
                corners = torch.einsum(
                    'ij,bkj->bki', l2e_t, ch)[..., :2]   # (N,4,2) ego
            xs, ys = corners[..., 0], corners[..., 1]
            x0 = ((xs.min(-1).values - x_min) / (x_max - x_min)
                  * self.bev_w).floor().long().clamp(0, self.bev_w - 1)
            x1 = ((xs.max(-1).values - x_min) / (x_max - x_min)
                  * self.bev_w).ceil().long().clamp(1, self.bev_w)
            # Y-AXIS CONTRACT (fixed 2026-08, see ISSUE.md P1-5): the BEV
            # feature row 0 is ego-y MINIMUM and the row index grows with
            # ego-y (rcsample create_grid_infos / bevdet gen_grid:
            # row i <-> y = y_min + i * y_step). The previous mapping
            # ``(y_max - ys.max)/range`` was MIRRORED — the occupancy GT
            # landed on the wrong side of the ego, so L_occ_gt supervised
            # s_occ with a flipped target and the Stage-4 occupancy boost
            # amplified the wrong cells (ghost-probe perception misaligned).
            y0 = ((ys.min(-1).values - y_min) / (y_max - y_min)
                  * self.bev_h).floor().long().clamp(0, self.bev_h - 1)
            y1 = ((ys.max(-1).values - y_min) / (y_max - y_min)
                  * self.bev_h).ceil().long().clamp(1, self.bev_h)
            for i in range(len(boxes)):
                occ[b, 0, y0[i]:y1[i], x0[i]:x1[i]] = 1.0
        return occ


